Fix compilation errors due to Android N release
getNextBuffer now only takes one argument.
Also fixed compilation warnings.

Change-Id: I3f07ba706c9155559d628526e5079a57c940d4fe
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-29312
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-30079
Signed-off-by: Markus Grape <markus.grape@intel.com>
Reviewed-on: https://android.intel.com:443/492529