Fix compilation error when using CLANG
Some parameters are unused and some parameters uses the
GNU field designator extension. Which causes this error
with CLANG: use of GNU old-style field designator extension.

This patch solve these errors.

Change-Id: Id823b27a7c3323ce1b6a9f9a663b52f8955cc46b
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-17022
Signed-off-by: Khaled Ben Amor <khaledx.ben.amor@intel.com>
Reviewed-on: https://android.intel.com:443/478803