[PFW] Correct PFW integration issue in audio HAL
Correct compilation errors caused by the integration of PFW
new release 3.2.1.

Change-Id: I05728b8a3be6529d096ed280e3271974032e3130
Tracked-On: https://jira01.devtools.intel.com/browse/OAM-6938
Signed-off-by: Khaled Ben Amor <khaledx.ben.amor@intel.com>
Reviewed-on: https://android.intel.com:443/447695